version: "3.9"

services:
  database:
    build: database
    image: database
    volumes:
      - ./database:/var/lib/mysql
  laravel:
    build: laravel
    image: laravel
    depends_on:
      - database
    ports:
      - "8000:8000"
    volumes:
      - ./laravel:/var/www/laravel
  node:
    build: node
    image: node
    ports:
      - "3000:3000"
    volumes:
      - ./node:/var/www/node
  vue:
    build: vue
    image: vue
    ports:
      - "8080:8080"
    volumes:
      - ./vue:/var/www/vue
  react:
    build: react
    image: react
    ports:
      - "3001:3001"
    volumes:
      - ./react:/var/www/react
